<%@ Page Title="" Language="C#" MasterPageFile="~/Vistas/PagMaestra.Master" AutoEventWireup="true" CodeBehind="UsuarioConsulta.aspx.cs" Inherits="Perrera.Vistas.UsuarioConsulta" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <header id="main-header">
        <div class="container">
            <div class="row end-sm end-md end-lg center-xs middle-xs middle-sm middle-md middle-lg">
                <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
                    <h1>Albergue
            <span class="primary-text">Municipal </span>
                    </h1>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10">
                    <nav id="navbar">
                        <ul>
                            <li>
                                <a href="Index.aspx">Inicio</a>
                            </li>
                            <li >
                                <a href="Adoptame.aspx">Adoptame</a>
                            </li>
                            <li>
                                <a href="Conocenos.aspx">Conócenos</a>
                            </li>
                            <li>
                                <a href="Fundaciones.aspx">Fundaciones</a>
                            </li>
                            <li>
                                <a href="Eventos.aspx">Eventos</a>
                            </li>
                            <li>
                                <a href="Sesion.aspx">Inicia Sesión</a>
                            </li>
                            <li>
                                <a href="Registrate.aspx">Registrate</a>
                            </li>
                            <li class="current"> 
                                <a href="UsuarioConsulta.aspx">Consulta</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <%--<form id="Form1" runat="server">
    <asp:GridView ID="GridView_Clientes"
        AutoGenerateColumns="False" 
        CssClass="table table-bordered bs-table" 
        DataKeyNames="ClienteID" 
        OnRowDeleted="GridView_Clientes_RowDeleted" 
        OnRowUpdated="GridView_Clientes_RowUpdated" 
        OnRowEditing="GridView_Clientes_RowEditing" 
        OnDataBound="GridView_Clientes_DataBound" 
        allowpaging="true"  runat="server">

       
    </asp:GridView>
        </form>--%>
    <br />
    <form runat="server">
        <asp:GridView ID="GridView1" CssClass="text-center" runat="server" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True"
            AutoGenerateSelectButton="True">

            <HeaderStyle BackColor="Pink" />
            <SelectedRowStyle BackColor="Highlight" />
            <SortedAscendingHeaderStyle BackColor="Blue" ForeColor="White" CssClass="AscHeader" />
            <SortedAscendingCellStyle BackColor="LightBlue" />
            <SortedDescendingHeaderStyle BackColor="Green" ForeColor="White" CssClass="DescHeader" />
            <SortedDescendingCellStyle BackColor="LightGreen"/>
        </asp:GridView>
    </form>


<%--    <form runat="server">
        <asp:GridView ID="GridView1" CssClass="text-center" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True"
            AutoGenerateSelectButton="True">

            <HeaderStyle BackColor="Pink" />
            <SelectedRowStyle BackColor="Highlight" />
            <SortedAscendingHeaderStyle BackColor="Blue" ForeColor="White" CssClass="AscHeader" />
            <SortedAscendingCellStyle BackColor="LightBlue" />
            <SortedDescendingHeaderStyle BackColor="Green" ForeColor="White" CssClass="DescHeader" />
            <SortedDescendingCellStyle BackColor="LightGreen" 
                
                />
        </asp:GridView>
    </form>

    <asp:gridview ID="Gridview1" runat="server" ShowFooter="true" AutoGenerateColumns="false" OnRowDeleting="Gridview1_RowDeleting">
                    <Columns>
                    <%--<asp:BoundField DataField="RowNumber" HeaderText="Row Number" />
                    <asp:TemplateField HeaderText="Column Name">
                        <ItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                        </ItemTemplate>
                    </asp:TemplateField>--%>

                 <%-- <asp:TemplateField HeaderText="Header 2">
                        <ItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                        </ItemTemplate>
                    </asp:TemplateField>--%>
                   <%-- <asp:TemplateField HeaderText="Data Type">
                        <%--<ItemTemplate>
                              <asp:DropDownList ID="ddldatatype" runat="server">
                              <asp:ListItem>varchar</asp:ListItem>
                              <asp:ListItem>int</asp:ListItem>
                              <asp:ListItem>numeric</asp:ListItem>
                              <asp:ListItem>uniqueidentifier</asp:ListItem>
                              <asp:ListItem>char</asp:ListItem>
                              </asp:DropDownList>
                        </ItemTemplate>--%>
                       <%-- <FooterStyle HorizontalAlign="Right" />
                        <FooterTemplate>
                        <asp:Button ID="ButtonAdd" runat="server" Text="Add New Row" OnClick="ButtonAdd_Click"/>
                         <asp:Button ID="ButtonDel" runat="server" Text="Delete Row" OnClick="ButtonDel_Click" />
                         <input type="hidden" runat="server" value="0" id="hiddencount" />
                        </FooterTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:LinkButton ID="lnkdelete" runat="server" CommandName="Delete" >Delete</asp:LinkButton>
                        </ItemTemplate>
                    </asp:TemplateField>
                    </Columns>
            </asp:gridview>--%>
    <br />
    
</asp:Content>
