-- --------------------------------------------------------
-- Host:                         198.71.225.54
-- Versión del servidor:         5.5.51-38.1-log - Percona Server (GPL), Release rel30.2, Revision 39.1
-- SO del servidor:              Linux
-- HeidiSQL Versión:             10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para Sistema_Transporte
CREATE DATABASE IF NOT EXISTS `Sistema_Transporte` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `Sistema_Transporte`;

-- Volcando estructura para tabla Sistema_Transporte.DATOS_EMPRESA
CREATE TABLE IF NOT EXISTS `DATOS_EMPRESA` (
  `NOMBRE` varchar(500) NOT NULL,
  `NIT` varchar(145) NOT NULL,
  `DIRECCION` varchar(145) NOT NULL,
  `LOGO` varchar(45) NOT NULL,
  `DATOS_EMPRESAcol` varchar(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.DATOS_EMPRESA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `DATOS_EMPRESA` DISABLE KEYS */;
/*!40000 ALTER TABLE `DATOS_EMPRESA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_ACCIDENTE
CREATE TABLE IF NOT EXISTS `ST_ACCIDENTE` (
  `ID_ACCIDENTE` int(11) NOT NULL,
  `ACC_DESCRIPCION` text NOT NULL,
  `ACC_SITIO` varchar(70) NOT NULL,
  `ACC_DATOS_INTERES` varchar(2000) DEFAULT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  PRIMARY KEY (`ID_ACCIDENTE`),
  KEY `fk_ST_ACCIDENTE_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  CONSTRAINT `fk_ST_ACCIDENTE_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_ACCIDENTE: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_ACCIDENTE` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_ACCIDENTE` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_ACCIDENTE_FOTO
CREATE TABLE IF NOT EXISTS `ST_ACCIDENTE_FOTO` (
  `ST_ID_FOTOS` int(11) NOT NULL,
  `ST_ID_ACCIDENTE` int(11) NOT NULL,
  `ACFO_FECHA` date NOT NULL,
  `ACFO_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  PRIMARY KEY (`ST_ID_FOTOS`,`ST_ID_ACCIDENTE`),
  KEY `fk_ST_FOTOS_has_ST_ACCIDENTE_ST_ACCIDENTE1_idx` (`ST_ID_ACCIDENTE`),
  KEY `fk_ST_FOTOS_has_ST_ACCIDENTE_ST_FOTOS1_idx` (`ST_ID_FOTOS`),
  CONSTRAINT `fk_ST_FOTOS_has_ST_ACCIDENTE_ST_FOTOS1` FOREIGN KEY (`ST_ID_FOTOS`) REFERENCES `ST_FOTOS` (`ID_FOTOS`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_FOTOS_has_ST_ACCIDENTE_ST_ACCIDENTE1` FOREIGN KEY (`ST_ID_ACCIDENTE`) REFERENCES `ST_ACCIDENTE` (`ID_ACCIDENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_ACCIDENTE_FOTO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_ACCIDENTE_FOTO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_ACCIDENTE_FOTO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_ASEGURADORA
CREATE TABLE IF NOT EXISTS `ST_ASEGURADORA` (
  `ID_SEGUROS` int(11) NOT NULL,
  `SEG_NOMBRE` varchar(100) NOT NULL,
  `SEG_NIT` varchar(45) NOT NULL,
  `SEG_TELEFONO` varchar(45) DEFAULT NULL,
  `SEG_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  PRIMARY KEY (`ID_SEGUROS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_ASEGURADORA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_ASEGURADORA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_ASEGURADORA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_CATEGORIA
CREATE TABLE IF NOT EXISTS `ST_CATEGORIA` (
  `ID_CATEGORIA` int(11) NOT NULL,
  `CAT_DESCRIPCION` varchar(75) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_CATEGORIA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_CATEGORIA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_CATEGORIA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_CODUCTOR
CREATE TABLE IF NOT EXISTS `ST_CODUCTOR` (
  `ID_CONDUCTOR` int(11) NOT NULL,
  `ID_ST_PERSONA` int(11) NOT NULL,
  `CON_NUMERO_LICENCIA` varchar(45) NOT NULL,
  `CON_FECHA_VENCIMIENTO_LIC` date NOT NULL,
  `CON_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  `CON_FOTOCOPIA_LICENCIA` varchar(145) DEFAULT NULL,
  PRIMARY KEY (`ID_CONDUCTOR`),
  KEY `fk_ST_CODUCTOR_ST_PERSONA1_idx` (`ID_ST_PERSONA`),
  CONSTRAINT `fk_ST_CODUCTOR_ST_PERSONA1` FOREIGN KEY (`ID_ST_PERSONA`) REFERENCES `ST_PERSONA` (`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_CODUCTOR: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_CODUCTOR` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_CODUCTOR` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_CONDUCTOR_VEHICULO
CREATE TABLE IF NOT EXISTS `ST_CONDUCTOR_VEHICULO` (
  `ID_ST_CODUCTOR` int(11) NOT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `ID_CONDUCTOR_VEHICULO` int(11) NOT NULL,
  `COVE_ESTADO` enum('ACVITVO','INACTIVO') NOT NULL,
  `COVE_FECHA_INICIO` date NOT NULL,
  `COVE_FECHA_FIN` date DEFAULT NULL,
  PRIMARY KEY (`ID_ST_CODUCTOR`,`ID_ST_VEHICULO`,`ID_CONDUCTOR_VEHICULO`),
  KEY `fk_ST_CODUCTOR_has_ST_VEHICULO_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  KEY `fk_ST_CODUCTOR_has_ST_VEHICULO_ST_CODUCTOR1_idx` (`ID_ST_CODUCTOR`),
  CONSTRAINT `fk_ST_CODUCTOR_has_ST_VEHICULO_ST_CODUCTOR1` FOREIGN KEY (`ID_ST_CODUCTOR`) REFERENCES `ST_CODUCTOR` (`ID_CONDUCTOR`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_CODUCTOR_has_ST_VEHICULO_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_CONDUCTOR_VEHICULO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_CONDUCTOR_VEHICULO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_CONDUCTOR_VEHICULO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_FOTOS
CREATE TABLE IF NOT EXISTS `ST_FOTOS` (
  `ID_FOTOS` int(11) NOT NULL,
  `FOT_NOMBRE` varchar(150) NOT NULL,
  `FOT_RUTA` varchar(100) NOT NULL,
  `FOT_FECHA` datetime NOT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `ID_ST_CATEGORIA` int(11) NOT NULL,
  PRIMARY KEY (`ID_FOTOS`),
  KEY `fk_ST_FOTOS_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  KEY `fk_ST_FOTOS_ST_CATEGORIA1_idx` (`ID_ST_CATEGORIA`),
  CONSTRAINT `fk_ST_FOTOS_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_FOTOS_ST_CATEGORIA1` FOREIGN KEY (`ID_ST_CATEGORIA`) REFERENCES `ST_CATEGORIA` (`ID_CATEGORIA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_FOTOS: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_FOTOS` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_FOTOS` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_LIQUIDACION
CREATE TABLE IF NOT EXISTS `ST_LIQUIDACION` (
  `ID_LIQUIDACION` int(11) NOT NULL,
  `LIQ_CONCEPTO` varchar(45) DEFAULT NULL,
  `LIQ_TOTAL` int(11) DEFAULT NULL,
  `LIQ_FECHA` date NOT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `ID_ST_RUTA` int(11) NOT NULL,
  PRIMARY KEY (`ID_LIQUIDACION`),
  KEY `fk_ST_LIQUIDACION_ST_VEHICULO_RUTA1_idx` (`ID_ST_VEHICULO`,`ID_ST_RUTA`),
  CONSTRAINT `fk_ST_LIQUIDACION_ST_VEHICULO_RUTA1` FOREIGN KEY (`ID_ST_VEHICULO`, `ID_ST_RUTA`) REFERENCES `ST_VEHICULO_RUTA` (`ID_ST_VEHICULO`, `ID_ST_RUTA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_LIQUIDACION: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_LIQUIDACION` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_LIQUIDACION` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_LLAMADOS_ATENCION
CREATE TABLE IF NOT EXISTS `ST_LLAMADOS_ATENCION` (
  `ID_LLAMADOS_ATENCION` int(11) NOT NULL,
  `LLAT_DESCRIPCION` text NOT NULL,
  `LLAT_GRAVEDAD` enum('BAJA','MEDIA','ALTA') NOT NULL,
  `ID_ST_CONDUCTOR` int(11) NOT NULL,
  PRIMARY KEY (`ID_LLAMADOS_ATENCION`),
  KEY `fk_ST_LLAMADOS_ATENCION_ST_CODUCTOR1_idx` (`ID_ST_CONDUCTOR`),
  CONSTRAINT `fk_ST_LLAMADOS_ATENCION_ST_CODUCTOR1` FOREIGN KEY (`ID_ST_CONDUCTOR`) REFERENCES `ST_CODUCTOR` (`ID_CONDUCTOR`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_LLAMADOS_ATENCION: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_LLAMADOS_ATENCION` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_LLAMADOS_ATENCION` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_MARCA
CREATE TABLE IF NOT EXISTS `ST_MARCA` (
  `ID_MARCA` int(11) NOT NULL,
  `MAR_NOMBRE` varchar(45) NOT NULL,
  `MAR_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  PRIMARY KEY (`ID_MARCA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_MARCA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_MARCA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_MARCA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_PERMISO
CREATE TABLE IF NOT EXISTS `ST_PERMISO` (
  `ID_PERMISO` int(11) NOT NULL,
  `PER_NOMBRE` varchar(50) NOT NULL,
  `PER_VISTA` varchar(150) NOT NULL,
  PRIMARY KEY (`ID_PERMISO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_PERMISO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_PERMISO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_PERMISO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_PERSONA
CREATE TABLE IF NOT EXISTS `ST_PERSONA` (
  `ID_PERSONA` int(11) NOT NULL,
  `PER_IDENTIFICACION` varchar(50) NOT NULL,
  `PER_NOMBRE` varchar(100) NOT NULL,
  `PER_APELLIDO` varchar(100) NOT NULL,
  `PER_DIRECCION` varchar(100) NOT NULL,
  `PER_CELULAR` varchar(50) NOT NULL,
  `PER_FOTO` varchar(400) DEFAULT NULL,
  `PER_EMAIL` varchar(100) NOT NULL,
  `PER_FOTOCOPIA_CEDULA` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID_PERSONA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_PERSONA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_PERSONA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_PERSONA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_PROPIETARIO
CREATE TABLE IF NOT EXISTS `ST_PROPIETARIO` (
  `ID_PROPIETARIO` int(11) NOT NULL,
  `PRO_FOTOCOPIA_TPROPIEDAD` varchar(400) DEFAULT NULL,
  `PRO_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  `ID_ST_PERSONA` int(11) NOT NULL,
  PRIMARY KEY (`ID_PROPIETARIO`),
  KEY `fk_ST_PROPIETARIO_ST_PERSONA1_idx` (`ID_ST_PERSONA`),
  CONSTRAINT `fk_ST_PROPIETARIO_ST_PERSONA1` FOREIGN KEY (`ID_ST_PERSONA`) REFERENCES `ST_PERSONA` (`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_PROPIETARIO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_PROPIETARIO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_PROPIETARIO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_PROPIETARIO_VEHICULO
CREATE TABLE IF NOT EXISTS `ST_PROPIETARIO_VEHICULO` (
  `ID_ST_PROPIETARIO` int(11) NOT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `PRVE_FECHA_REGISTRO` date NOT NULL,
  `PRVE_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  `PRVE_FECHA_FIN` date DEFAULT NULL,
  PRIMARY KEY (`ID_ST_PROPIETARIO`,`ID_ST_VEHICULO`),
  KEY `fk_ST_PROPIETARIO_has_ST_VEHICULO_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  KEY `fk_ST_PROPIETARIO_has_ST_VEHICULO_ST_PROPIETARIO1_idx` (`ID_ST_PROPIETARIO`),
  CONSTRAINT `fk_ST_PROPIETARIO_has_ST_VEHICULO_ST_PROPIETARIO1` FOREIGN KEY (`ID_ST_PROPIETARIO`) REFERENCES `ST_PROPIETARIO` (`ID_PROPIETARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_PROPIETARIO_has_ST_VEHICULO_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_PROPIETARIO_VEHICULO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_PROPIETARIO_VEHICULO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_PROPIETARIO_VEHICULO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_PUNTO_CONTROL
CREATE TABLE IF NOT EXISTS `ST_PUNTO_CONTROL` (
  `ID_PUNTO_CONTROL` int(11) NOT NULL,
  `PUCO_NOMBRE` varchar(100) NOT NULL,
  `PUCO_LONGITUD` varchar(45) NOT NULL,
  `PUCO_LATITUD` varchar(45) NOT NULL,
  `PUCO_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  PRIMARY KEY (`ID_PUNTO_CONTROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_PUNTO_CONTROL: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_PUNTO_CONTROL` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_PUNTO_CONTROL` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_ROL
CREATE TABLE IF NOT EXISTS `ST_ROL` (
  `ID_ROL` int(11) NOT NULL,
  `ROL_NOMBRE` varchar(100) NOT NULL,
  `ROL_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  PRIMARY KEY (`ID_ROL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_ROL: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_ROL` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_ROL` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_ROL_PERMISO
CREATE TABLE IF NOT EXISTS `ST_ROL_PERMISO` (
  `ID_ST_ROL` int(11) NOT NULL,
  `ID_ST_PERMISO` int(11) NOT NULL,
  `ROPE_FECHA_ASIGNACION` datetime NOT NULL,
  PRIMARY KEY (`ID_ST_ROL`,`ID_ST_PERMISO`),
  KEY `fk_ST_ROL_has_ST_PERMISO_ST_PERMISO1_idx` (`ID_ST_PERMISO`),
  KEY `fk_ST_ROL_has_ST_PERMISO_ST_ROL1_idx` (`ID_ST_ROL`),
  CONSTRAINT `fk_ST_ROL_has_ST_PERMISO_ST_ROL1` FOREIGN KEY (`ID_ST_ROL`) REFERENCES `ST_ROL` (`ID_ROL`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_ROL_has_ST_PERMISO_ST_PERMISO1` FOREIGN KEY (`ID_ST_PERMISO`) REFERENCES `ST_PERMISO` (`ID_PERMISO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_ROL_PERMISO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_ROL_PERMISO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_ROL_PERMISO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_RUTA
CREATE TABLE IF NOT EXISTS `ST_RUTA` (
  `ID_RUTA` int(11) NOT NULL,
  `RUT_NOMBRE` varchar(100) NOT NULL,
  `RUT_ORIGEN` varchar(100) NOT NULL,
  `RUT_FINAL` varchar(45) NOT NULL,
  `RUT_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  PRIMARY KEY (`ID_RUTA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_RUTA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_RUTA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_RUTA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_RUTA_PUNTO_CONTROL
CREATE TABLE IF NOT EXISTS `ST_RUTA_PUNTO_CONTROL` (
  `ID_ST_RUTA` int(11) NOT NULL,
  `ID_ST_PUNTO_CONTROL` int(11) NOT NULL,
  `RPC_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  PRIMARY KEY (`ID_ST_RUTA`,`ID_ST_PUNTO_CONTROL`),
  KEY `fk_ST_RUTAS_has_ST_PUNTO_CONTROL_ST_PUNTO_CONTROL1_idx` (`ID_ST_PUNTO_CONTROL`),
  KEY `fk_ST_RUTAS_has_ST_PUNTO_CONTROL_ST_RUTAS1_idx` (`ID_ST_RUTA`),
  CONSTRAINT `fk_ST_RUTAS_has_ST_PUNTO_CONTROL_ST_RUTAS1` FOREIGN KEY (`ID_ST_RUTA`) REFERENCES `ST_RUTA` (`ID_RUTA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_RUTAS_has_ST_PUNTO_CONTROL_ST_PUNTO_CONTROL1` FOREIGN KEY (`ID_ST_PUNTO_CONTROL`) REFERENCES `ST_PUNTO_CONTROL` (`ID_PUNTO_CONTROL`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_RUTA_PUNTO_CONTROL: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_RUTA_PUNTO_CONTROL` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_RUTA_PUNTO_CONTROL` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_TIPO_COMBUSTIBLE
CREATE TABLE IF NOT EXISTS `ST_TIPO_COMBUSTIBLE` (
  `ID_TIPO_COMBUSTIBLE` int(11) NOT NULL,
  `TICOM_NOMBRE` varchar(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_COMBUSTIBLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_TIPO_COMBUSTIBLE: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_TIPO_COMBUSTIBLE` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_TIPO_COMBUSTIBLE` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_USUARIO
CREATE TABLE IF NOT EXISTS `ST_USUARIO` (
  `ID_USUARIO` int(11) NOT NULL,
  `USU_NOMBRE` varchar(100) NOT NULL,
  `USU_CONTRASENA` varchar(100) NOT NULL,
  `USU_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  `ID_ST_PERSONA` int(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `fk_ST_USUARIO_ST_PERSONA_idx` (`ID_ST_PERSONA`),
  CONSTRAINT `fk_ST_USUARIO_ST_PERSONA` FOREIGN KEY (`ID_ST_PERSONA`) REFERENCES `ST_PERSONA` (`ID_PERSONA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_USUARIO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_USUARIO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_USUARIO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_USUARIO_ROL
CREATE TABLE IF NOT EXISTS `ST_USUARIO_ROL` (
  `ID_ST_USUARIO` int(11) NOT NULL,
  `ID_ST_ROL` int(11) NOT NULL,
  `USRO_FECHA_ASIGNACION` datetime NOT NULL,
  PRIMARY KEY (`ID_ST_USUARIO`,`ID_ST_ROL`),
  KEY `fk_ST_USUARIO_has_ST_ROL_ST_ROL1_idx` (`ID_ST_ROL`),
  KEY `fk_ST_USUARIO_has_ST_ROL_ST_USUARIO1_idx` (`ID_ST_USUARIO`),
  CONSTRAINT `fk_ST_USUARIO_has_ST_ROL_ST_USUARIO1` FOREIGN KEY (`ID_ST_USUARIO`) REFERENCES `ST_USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_USUARIO_has_ST_ROL_ST_ROL1` FOREIGN KEY (`ID_ST_ROL`) REFERENCES `ST_ROL` (`ID_ROL`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_USUARIO_ROL: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_USUARIO_ROL` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_USUARIO_ROL` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_VEHICULO
CREATE TABLE IF NOT EXISTS `ST_VEHICULO` (
  `ID_VEHICULO` int(11) NOT NULL,
  `VEH_NUM_MOTOR` varchar(45) NOT NULL,
  `VEH_NUM_CHASIS` varchar(45) NOT NULL,
  `VEH_FECHA_MATRICULA` datetime NOT NULL,
  `VEH_COLOR` varchar(45) NOT NULL,
  `VEH_MODELO` date NOT NULL,
  `VEH_CAPACIDAD` int(11) NOT NULL,
  `VEH_PLACA` varchar(15) NOT NULL,
  `VEH_CILINDRAJE` int(11) NOT NULL,
  `VEH_KILOMETRAJE_ACTUAL` int(11) NOT NULL,
  `VEH_NUMERO_INTERNO` int(11) NOT NULL,
  `VEH_LIMITACION_PROPIEDAD` text,
  `VEH_CANTIDAD_TOPE` int(11) NOT NULL,
  `VEH_ESTADO` enum('ACTIVO','INACTIVO') DEFAULT NULL,
  `ID_ST_MARCA` int(11) NOT NULL,
  `ID_ST_TIPO_COMBUSTIBLE` int(11) NOT NULL,
  PRIMARY KEY (`ID_VEHICULO`),
  UNIQUE KEY `VEH_NUM_MOTOR_UNIQUE` (`VEH_NUM_MOTOR`),
  UNIQUE KEY `VEH_NUM_CHASIS_UNIQUE` (`VEH_NUM_CHASIS`),
  KEY `fk_ST_VEHICULO_ST_MARCA1_idx` (`ID_ST_MARCA`),
  KEY `fk_ST_VEHICULO_ST_TIPO_COMBUSTIBLE1_idx` (`ID_ST_TIPO_COMBUSTIBLE`),
  CONSTRAINT `fk_ST_VEHICULO_ST_MARCA1` FOREIGN KEY (`ID_ST_MARCA`) REFERENCES `ST_MARCA` (`ID_MARCA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_VEHICULO_ST_TIPO_COMBUSTIBLE1` FOREIGN KEY (`ID_ST_TIPO_COMBUSTIBLE`) REFERENCES `ST_TIPO_COMBUSTIBLE` (`ID_TIPO_COMBUSTIBLE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_VEHICULO: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_VEHICULO` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_VEHICULO` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_VEHICULO_ASEGURADORA
CREATE TABLE IF NOT EXISTS `ST_VEHICULO_ASEGURADORA` (
  `ID_ST_SEGURO` int(11) NOT NULL,
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `ID_VEHICULO_SEGURO` int(11) NOT NULL,
  `VESE_FECHA_INICIO` date NOT NULL,
  `VESE_FECHA_VENCIMIENTO` date NOT NULL,
  `VESE_NUMERO` varchar(45) NOT NULL,
  `VESE_ESTADO` enum('ACTIVO','INACTIVO') NOT NULL,
  `VESE_OBLIGATORIEDAD` enum('ACTIVO','INACTIVO') NOT NULL,
  PRIMARY KEY (`ID_ST_SEGURO`,`ID_ST_VEHICULO`,`ID_VEHICULO_SEGURO`),
  KEY `fk_ST_SEGUROS_has_ST_VEHICULO_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  KEY `fk_ST_SEGUROS_has_ST_VEHICULO_ST_SEGUROS1_idx` (`ID_ST_SEGURO`),
  CONSTRAINT `fk_ST_SEGUROS_has_ST_VEHICULO_ST_SEGUROS1` FOREIGN KEY (`ID_ST_SEGURO`) REFERENCES `ST_ASEGURADORA` (`ID_SEGUROS`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_SEGUROS_has_ST_VEHICULO_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_VEHICULO_ASEGURADORA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_VEHICULO_ASEGURADORA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_VEHICULO_ASEGURADORA` ENABLE KEYS */;

-- Volcando estructura para tabla Sistema_Transporte.ST_VEHICULO_RUTA
CREATE TABLE IF NOT EXISTS `ST_VEHICULO_RUTA` (
  `ID_ST_VEHICULO` int(11) NOT NULL,
  `ID_ST_RUTA` int(11) NOT NULL,
  `VERU_TOTAL_PASAJEROS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_ST_VEHICULO`,`ID_ST_RUTA`),
  KEY `fk_ST_VEHICULO_has_ST_RUTAS_ST_RUTAS1_idx` (`ID_ST_RUTA`),
  KEY `fk_ST_VEHICULO_has_ST_RUTAS_ST_VEHICULO1_idx` (`ID_ST_VEHICULO`),
  CONSTRAINT `fk_ST_VEHICULO_has_ST_RUTAS_ST_VEHICULO1` FOREIGN KEY (`ID_ST_VEHICULO`) REFERENCES `ST_VEHICULO` (`ID_VEHICULO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ST_VEHICULO_has_ST_RUTAS_ST_RUTAS1` FOREIGN KEY (`ID_ST_RUTA`) REFERENCES `ST_RUTA` (`ID_RUTA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Volcando datos para la tabla Sistema_Transporte.ST_VEHICULO_RUTA: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ST_VEHICULO_RUTA` DISABLE KEYS */;
/*!40000 ALTER TABLE `ST_VEHICULO_RUTA` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
